name: login_bloc
description: "Aplicativo de login com Bloc"
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  formz: ^0.8.0 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true